# Lift and coverage for tops

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os
sys.path.append(os.path.abspath('..'))
import dstools.ml.metrics as mx

In [2]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.model_selection import train_test_split

import seaborn as sns
sns.set_palette("deep", desat=.6)

ds = pd.read_csv('titanic.csv')

features = pd.get_dummies(ds.drop(['survived', 'alive'], axis=1)).fillna(0)
target = ds.survived
split = train_test_split(features, target, test_size=0.5)
x_train, x_test, y_train, y_test = split

y_score = RandomForestClassifier().fit(x_train, y_train).predict_proba(x_test)

mx.lift(y_test, y_score[:, 1], n_buckets=10)

,cnt,target_cnt,target_cnt_cum,cnt_cum,target_share,target_share_cum,lift,cum_lift,coverage
top,,,,,,,,,
1,45,40,40,45,0.888889,0.888889,2.304910,2.304910,0.232558
2,45,38,78,90,0.844444,0.866667,2.189664,2.247287,0.453488
3,45,30,108,135,0.666667,0.800000,1.728682,2.074419,0.627907
4,45,11,119,180,0.244444,0.661111,0.633850,1.714276,0.691860
5,45,20,139,225,0.444444,0.617778,1.152455,1.601912,0.808140
6,45,10,149,270,0.222222,0.551852,0.576227,1.430965,0.866279
7,44,11,160,314,0.250000,0.509554,0.648256,1.321286,0.930233
8,44,7,167,358,0.159091,0.466480,0.412526,1.209595,0.970930
9,44,1,168,402,0.022727,0.417910,0.058932,1.083652,0.976744
10,44,4,172,446,0.090909,0.385650,0.235729,1.000000,1.000000